// /**
//  * @fileoverview This file is generated by the Angular template compiler.
//  * Do not edit.
//  * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
//  */
//  /* tslint:disable */


// import * as i0 from '@angular/core';
// import * as i1 from './studiox.module';
// import * as i2 from '@angular/http';
// import * as i3 from './message/message.service';
// import * as i4 from './log/log.service';
// import * as i5 from './studioxHttp';
// import * as i6 from './session/studiox-session.service';
// import * as i7 from './auth/permission-checker.service';
// import * as i8 from './features/feature-checker.service';
// import * as i9 from './localization/localization.service';
// import * as i10 from './settings/setting.service';
// import * as i11 from './notify/notify.service';
// import * as i12 from './multi-tenancy/studiox-multi-tenancy.service';
// import * as i13 from './studiox-user-configuration.service';
// import * as i14 from './auth/token.service';
// import * as i15 from './utils/utils.service';
// export const StudioXModuleNgFactory:i0.NgModuleFactory<i1.StudioXModule> = i0.ɵcmf(i1.StudioXModule,
//     ([] as any[]),(_l:any) => {
//       return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
//           [[8,([] as any[])],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(4608,
//           i2.BrowserXhr,i2.BrowserXhr,([] as any[])),i0.ɵmpd(4608,i2.ResponseOptions,
//           i2.BaseResponseOptions,([] as any[])),i0.ɵmpd(5120,i2.XSRFStrategy,i2.ɵb,
//           ([] as any[])),i0.ɵmpd(4608,i2.XHRBackend,i2.XHRBackend,[i2.BrowserXhr,i2.ResponseOptions,
//           i2.XSRFStrategy]),i0.ɵmpd(4608,i2.RequestOptions,i2.BaseRequestOptions,([] as any[])),
//           i0.ɵmpd(4608,i3.MessageService,i3.MessageService,([] as any[])),i0.ɵmpd(4608,
//               i4.LogService,i4.LogService,([] as any[])),i0.ɵmpd(4608,i5.StudioXHttpConfiguration,
//               i5.StudioXHttpConfiguration,[i3.MessageService,i4.LogService]),i0.ɵmpd(5120,
//               i2.Http,i1.studioxHttpFactory,[i2.XHRBackend,i2.RequestOptions,i5.StudioXHttpConfiguration]),
//           i0.ɵmpd(4608,i2.ɵg,i2.ɵg,([] as any[])),i0.ɵmpd(4608,i2.JSONPBackend,i2.ɵa,
//               [i2.ɵg,i2.ResponseOptions]),i0.ɵmpd(5120,i2.Jsonp,i2.ɵd,[i2.JSONPBackend,
//               i2.RequestOptions]),i0.ɵmpd(4608,i6.StudioXSessionService,i6.StudioXSessionService,
//               ([] as any[])),i0.ɵmpd(4608,i7.PermissionCheckerService,i7.PermissionCheckerService,
//               ([] as any[])),i0.ɵmpd(4608,i8.FeatureCheckerService,i8.FeatureCheckerService,
//               ([] as any[])),i0.ɵmpd(4608,i9.LocalizationService,i9.LocalizationService,
//               ([] as any[])),i0.ɵmpd(4608,i10.SettingService,i10.SettingService,([] as any[])),
//           i0.ɵmpd(4608,i11.NotifyService,i11.NotifyService,([] as any[])),i0.ɵmpd(4608,
//               i12.StudioXMultiTenancyService,i12.StudioXMultiTenancyService,([] as any[])),
//           i0.ɵmpd(4608,i13.StudioXUserConfigurationService,i13.StudioXUserConfigurationService,
//               [i2.Http]),i0.ɵmpd(4608,i14.TokenService,i14.TokenService,([] as any[])),
//           i0.ɵmpd(4608,i15.UtilsService,i15.UtilsService,([] as any[])),i0.ɵmpd(512,
//               i2.HttpModule,i2.HttpModule,([] as any[])),i0.ɵmpd(512,i2.JsonpModule,
//               i2.JsonpModule,([] as any[])),i0.ɵmpd(512,i1.StudioXModule,i1.StudioXModule,
//               ([] as any[]))]);
//     });
// //# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovR2l0aHViL2FicC1uZzItbW9kdWxlL3NyYy9hYnAubW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0Q6L0dpdGh1Yi9hYnAtbmcyLW1vZHVsZS9zcmMvYWJwLm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9